#!/usr/bin/env python3
"""Collect every spoken line in the library into one recording script per
language.

    python scripts/build_audio_script.py

The exercise files are the source of truth for what the app says: each
`audio.events` entry carries the text, the asset key and the exact file the
player will look for. Whoever records the voice pack — a person in a booth or
scripts/generate_voice.py — needs that as one ordered list per language, not
spread across thirteen YAML files, so it is generated here.

Lines whose `asset_key` starts with `common.` are recorded once and reused by
every exercise (docs/AUDIO_SPEC.md). A line already on disk is marked as
recorded, so the script doubles as the progress report for the voice pack.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(errors="replace")

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
OUT_DIR = ROOT / "docs/generated"

LANGUAGES = ("uk", "en")

# The preparation countdown is spoken from the global pack rather than per
# exercise (docs/AUDIO_SPEC.md, "Common reusable").
COUNTDOWN = {
    "uk": {5: "П'ять.", 4: "Чотири.", 3: "Три.", 2: "Два.", 1: "Один."},
    "en": {5: "Five.", 4: "Four.", 3: "Three.", 2: "Two.", 1: "One."},
}

WORDS = {
    "uk": {
        "title": "Сценарій озвучки",
        "generated": "Згенеровано `scripts/build_audio_script.py` з `data/exercises/**.yaml`.",
        "do_not_edit": "Не редагувати вручну: правити треба текст репліки у файлі вправи.",
        "style": (
            "**Стиль:** спокійний, доброзичливий, чіткий, без поспіху, короткі фрази. "
            "Не говорити поверх критичної команди руху (docs/AUDIO_SPEC.md)."
        ),
        "format": (
            "**Формат:** майстер WAV, нормалізований, із підрізаною тишею; "
            "доставка в застосунок — M4A/AAC за шляхом із колонки «Файл»."
        ),
        "modes": (
            "**Режими голосу:** «завжди» звучить у будь-якому режимі; репліки режимів "
            "«Слова руху» та «Лічба» звучать лише тоді, коли користувач обрав цей режим "
            "у Налаштуваннях, і мають бути короткими — вони мусять вкластися в половину "
            "циклу руху (близько двох секунд)."
        ),
        "progress": "Записано {0} із {1} реплік.",
        "common_title": "## Спільні репліки",
        "common_note": "Записуються один раз і використовуються всіма вправами.",
        "common_head": "| Текст | Коли | Файл | Використовує | Стан |",
        "rows_head": "| Репліка | Коли | Текст | Файл | Стан |",
        "recorded": "записано",
        "todo": "потрібно записати",
        "no_path": "немає шляху",
        "countdown": "відлік підготовки",
        "always": "завжди",
        "phase_words": "режим «Слова руху»",
        "count": "режим «Лічба»",
        "missing": "_Немає тексту цією мовою._",
    },
    "en": {
        "title": "Voice recording script",
        "generated": "Generated by `scripts/build_audio_script.py` from `data/exercises/**.yaml`.",
        "do_not_edit": "Do not edit by hand: change the cue text in the exercise file instead.",
        "style": (
            "**Style:** calm, friendly, clear, unhurried, short phrases. Never speak over "
            "a critical movement command (docs/AUDIO_SPEC.md)."
        ),
        "format": (
            "**Format:** WAV master, normalized, silence trimmed; delivered to the app as "
            "M4A/AAC at the path in the File column."
        ),
        "modes": (
            "**Voice modes:** \"always\" is spoken in every mode; the movement-words and "
            "counting lines are spoken only when the listener has picked that mode in "
            "Settings, and must be short — they have to fit inside half a movement cycle, "
            "about two seconds."
        ),
        "progress": "Recorded {0} of {1} lines.",
        "common_title": "## Shared lines",
        "common_note": "Recorded once and reused by every exercise.",
        "common_head": "| Text | When | File | Used by | State |",
        "rows_head": "| Cue | When | Text | File | State |",
        "recorded": "recorded",
        "todo": "to record",
        "no_path": "no path",
        "countdown": "preparation countdown",
        "always": "always",
        "phase_words": "movement words mode",
        "count": "counting mode",
        "missing": "_No text in this language._",
    },
}


def load(path: Path):
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def escape(text: str) -> str:
    """Markdown table cells cannot carry a raw pipe or a line break."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def exercise_count(count: int, lang: str) -> str:
    if lang != "uk":
        return "{0} exercise{1}".format(count, "" if count == 1 else "s")
    # 1 вправа, 2-4 вправи, 5+ вправ - the report reads as prose.
    tail = count % 100
    if 11 <= tail <= 14:
        return "{0} вправ".format(count)
    last = count % 10
    if last == 1:
        return "{0} вправа".format(count)
    if 2 <= last <= 4:
        return "{0} вправи".format(count)
    return "{0} вправ".format(count)


def localized(target: str, lang: str) -> str:
    """`audio/uk/...` as authored -> the same file under [lang]."""
    parts = target.split("/")
    if len(parts) >= 3 and parts[0] == "audio":
        parts[1] = lang
    return "/".join(parts)


def build(lang: str) -> tuple[int, int]:
    words = WORDS[lang]
    index = load(DATA / "exercises/index.yaml")

    def status(target: str | None) -> str:
        if not target:
            return words["no_path"]
        return words["recorded"] if (ROOT / target).exists() else words["todo"]

    def when(mode) -> str:
        return {
            None: words["always"],
            "phase_words": words["phase_words"],
            "count": words["count"],
        }.get(mode, str(mode))

    # target file -> {text, mode, used_by}
    common: dict[str, dict] = {}
    for seconds, text in COUNTDOWN[lang].items():
        common["audio/{0}/common/countdown_{1}.m4a".format(lang, seconds)] = {
            "text": text,
            "mode": None,
            "used_by": [words["countdown"]],
        }

    sections: list[str] = []
    total = 0
    recorded = 0

    for entry in index["exercises"]:
        raw = load(DATA / "exercises" / entry["file"])
        ex_id = raw["exercise"]["id"]
        title = raw.get("locale", {}).get("uk", {}).get("title", ex_id)
        rows: list[str] = []
        gaps = 0

        for event in raw.get("audio", {}).get("events", []):
            if not event.get("text_uk"):
                continue
            text = event.get("text_" + lang)
            target = localized(event.get("target_file") or "", lang)
            mode = event.get("voice_mode")
            if not text:
                gaps += 1
                continue
            if str(event.get("asset_key", "")).startswith("common."):
                shared = common.setdefault(
                    target, {"text": text, "mode": mode, "used_by": []}
                )
                shared["used_by"].append(ex_id)
                continue
            total += 1
            state = status(target)
            if state == words["recorded"]:
                recorded += 1
            rows.append(
                "| `{0}` | {1} | {2} | `{3}` | {4} |".format(
                    event["id"], when(mode), escape(text), target, state
                )
            )

        if not rows and not gaps:
            continue
        sections.append("## {0} — {1}\n".format(ex_id, title))
        if gaps and not rows:
            sections.append(words["missing"])
            sections.append("")
            continue
        sections.append(words["rows_head"])
        sections.append("|---|---|---|---|---|")
        sections.extend(rows)
        sections.append("")

    common_rows: list[str] = []
    for target in sorted(common):
        item = common[target]
        total += 1
        state = status(target)
        if state == words["recorded"]:
            recorded += 1
        users = item["used_by"]
        used = users[0] if len(users) == 1 else exercise_count(len(users), lang)
        common_rows.append(
            "| {0} | {1} | `{2}` | {3} | {4} |".format(
                escape(item["text"]), when(item["mode"]), target, used, state
            )
        )

    head = [
        "# {0} — {1}".format(words["title"], lang),
        "",
        words["generated"],
        words["do_not_edit"],
        "",
        words["style"],
        "",
        words["format"],
        "",
        words["modes"],
        "",
        words["progress"].format(recorded, total),
        "",
        words["common_title"],
        "",
        words["common_note"],
        "",
        words["common_head"],
        "|---|---|---|---|---|",
    ]

    out = OUT_DIR / "AUDIO_SCRIPT_{0}.md".format(lang.upper())
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "\n".join(head + common_rows + [""] + sections).rstrip() + "\n",
        encoding="utf-8",
    )
    print("OK: {0}  ({1}/{2} recorded)".format(out.relative_to(ROOT), recorded, total))
    return recorded, total


def main() -> int:
    # The single-language file this replaced.
    legacy = OUT_DIR / "AUDIO_SCRIPT.md"
    if legacy.exists():
        legacy.unlink()
    for lang in LANGUAGES:
        build(lang)
    return 0


if __name__ == "__main__":
    sys.exit(main())
